### ISSUE TITLE
5.0.3 Still have issue related to PendingIntent

### ISSUE THREAD

**Issue by HenryWu01** [Justson/Downloader#31]
I'm using ``implementation 'com.github.Justson:Downloader:v5.0.3-androidx' // AgentWeb (Downloader)``

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-22
E/AndroidRuntime: Process: ***.***.***, PID: 1851
E/AndroidRuntime: java.lang.IllegalArgumentException: ***.***.***: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime:       at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime:       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime:       at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime:       at com.download.library.DownloadNotifier.buildCancelContent(DownloadNotifier.java:147)
E/AndroidRuntime:       at com.download.library.DownloadNotifier.initBuilder(DownloadNotifier.java:123)
E/AndroidRuntime:       at com.download.library.DownloadTask.createNotifier(DownloadTask.java:508)
E/AndroidRuntime:       at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:178)
E/AndroidRuntime:       at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
E/AndroidRuntime:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime:       at java.lang.Thread.run(Thread.java:920)
```

**Comment by HenryWu01** [comment]
看起来``buildCancelContent``没有处理，最新版5.0.3的处理不完全。

**Comment by HenryWu01** [comment]
master分支看上去没有问题，但是到了tag里有些commit就没了

**Comment by Justson** [comment]
implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
